# Generated by Django 5.0.4 on 2024-05-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
